### ISSUE TITLE
create and apply schema snapshots

### ISSUE THREAD

**Issue by thwarted** [EasyPost/rmmm#4]
It would be nice to be able to snapshot the schema to a single file after applying all the migrations, and then load that snapshot via rmmm (so the interface to creating and applying a snapshot is the same, through this tool).  This will optimize setting up an empty database so it doesn't require going through all the migrations individually (which may have churn on various DDL state).

I also have a set of historical migrations that require setting some global mysql variables in order to apply (`log_bin_trust_function_creators` for creation of stored procedures) that I'd like to not have to frob in order to bring up a fresh database.  Creating it from a final form would avoid that.

**Comment by Roguelazer** [comment]
snapshots are already created after every migration (in `db/structure.sql`) so this is really a question of applying them.
